// Autogenerated by firmware-libraries/SerialComms/python/cmd_template_parser.py on Sat Aug  7 02:32:37 2021

#include "pack_cmd_defines.h"
Cmd_Pointer cmds_ptr[NUM_CMD_ITEMS] = {

set_vlv,
send_telem_short,
send_telem_all,
set_stepper_period,
set_stepper_direction,
set_kp,
set_ki,
set_kd,
set_control_calc_period,
set_state,
move_stepper_degrees,
download_flash,
wipe_flash,
start_logging,
stop_logging,
set_stepper_pos,
set_stepper_zero,
set_control_target_pressure,
ambientize_pressure_transducers,
set_low_toggle_percent,
set_high_toggle_percent,
set_control_loop_duration,
set_stepper_speed,
set_telem,
set_presstank_status,
ambientize_pot,
set_system_clock,
};

int16_t command_map[COMMAND_MAP_SZ] = {-1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, -1, -1, 26, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};
int16_t command_sz[COMMAND_MAP_SZ] = {-1, -1, -1, -1, -1, -1, -1, -1, 17, 13, 13, 15, 14, 21, 21, 21, 13, 13, 15, 12, 12, 12, 12, 17, 13, 17, 12, 17, 17, 16, 15, 13, 14, 13, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};
