/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// pack_calibration_defines.c
/// Autogenerated by firmware-libraries/SerialComms/python/calibration_file_generator.py on Sun Aug  8 23:48:36 2021

#include "pack_calibration_defines.h"

void pack_calibration_data(uint8_t* dst){
	*(dst + 0) = CALIBRATION_ITEM_0;
	*(dst + 1) = CALIBRATION_ITEM_1;
	*(dst + 2) = CALIBRATION_ITEM_2;
	*(dst + 3) = CALIBRATION_ITEM_3;
	*(dst + 4) = CALIBRATION_ITEM_4;
	*(dst + 5) = CALIBRATION_ITEM_5;
	*(dst + 6) = CALIBRATION_ITEM_6;
	*(dst + 7) = CALIBRATION_ITEM_7;
	*(dst + 8) = CALIBRATION_ITEM_8;
	*(dst + 9) = CALIBRATION_ITEM_9;
	*(dst + 10) = CALIBRATION_ITEM_10;
	*(dst + 11) = CALIBRATION_ITEM_11;
	*(dst + 12) = CALIBRATION_ITEM_12;
	*(dst + 13) = CALIBRATION_ITEM_13;
	*(dst + 14) = CALIBRATION_ITEM_14;
	*(dst + 15) = CALIBRATION_ITEM_15;
	*(dst + 16) = CALIBRATION_ITEM_16;
	*(dst + 17) = CALIBRATION_ITEM_17;
	*(dst + 18) = CALIBRATION_ITEM_18;
	*(dst + 19) = CALIBRATION_ITEM_19;
	*(dst + 20) = CALIBRATION_ITEM_20;
	*(dst + 21) = CALIBRATION_ITEM_21;
	*(dst + 22) = CALIBRATION_ITEM_22;
	*(dst + 23) = CALIBRATION_ITEM_23;
	*(dst + 24) = CALIBRATION_ITEM_24;
	*(dst + 25) = CALIBRATION_ITEM_25;
	*(dst + 26) = CALIBRATION_ITEM_26;
	*(dst + 27) = CALIBRATION_ITEM_27;
	*(dst + 28) = CALIBRATION_ITEM_28;
	*(dst + 29) = CALIBRATION_ITEM_29;
	*(dst + 30) = CALIBRATION_ITEM_30;
	*(dst + 31) = CALIBRATION_ITEM_31;
	*(dst + 32) = CALIBRATION_ITEM_32;
	*(dst + 33) = CALIBRATION_ITEM_33;
	*(dst + 34) = CALIBRATION_ITEM_34;
	*(dst + 35) = CALIBRATION_ITEM_35;
}