// Autogenerated by firmware-libraries/SerialComms/python/cmd_template_parser.py on Sat Aug  7 02:32:37 2021

#include <stdint.h>

// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
#include "autosequence.h"  // for set_state()
#include "serial_data.h"   // flash and telem
#include "globals.h"       // for setting constants
#include "valves.h"        // manual valve control
#include "constants.h"
#include "status_flags.h"
#include "tank_pressure_control.h"
#include "nonvolatile_memory.h"
#include "calibrations.h"

#include "W25N01GV.h"
#include "L6470.h"


extern W25N01GV_Flash flash;
extern uint8_t telem_disabled;

extern TPC_Info tanks[NUM_TANKS];

extern TIM_HandleTypeDef TIM_MICROS;

// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

void set_vlv(uint8_t* data, uint8_t* status){

	uint32_t vlv_num = (data[3]<<24|data[2]<<16|data[1]<<8|data[0])/1;
	uint8_t state = (data[4])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	set_valve_channel(vlv_num, state);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void send_telem_short(uint8_t* data, uint8_t* status){

	uint8_t board_num = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void send_telem_all(uint8_t* data, uint8_t* status){

	uint8_t board_num = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_stepper_period(uint8_t* data, uint8_t* status){

	uint8_t stepper_num = (data[0])/1;
	uint16_t period = (data[2]<<8|data[1])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_stepper_direction(uint8_t* data, uint8_t* status){

	uint8_t stepper_num = (data[0])/1;
	int8_t direction = (data[1])/1.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_kp(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	double gain = (data[8]<<56|data[7]<<48|data[6]<<40|data[5]<<32|data[4]<<24|data[3]<<16|data[2]<<8|data[1])/100.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
		tanks[motor_num].K_p = gain;  // control
		save_nonvolatile_variables();
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_ki(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	double gain = (data[8]<<56|data[7]<<48|data[6]<<40|data[5]<<32|data[4]<<24|data[3]<<16|data[2]<<8|data[1])/100.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
		tanks[motor_num].K_i = gain;  // control
		save_nonvolatile_variables();
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_kd(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	double gain = (data[8]<<56|data[7]<<48|data[6]<<40|data[5]<<32|data[4]<<24|data[3]<<16|data[2]<<8|data[1])/100.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
		tanks[motor_num].K_d = gain;
		save_nonvolatile_variables();
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_control_calc_period(uint8_t* data, uint8_t* status){

	uint8_t period = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_state(uint8_t* data, uint8_t* status){

	uint8_t next_state = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	manual_state_transition(next_state);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void move_stepper_degrees(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	uint16_t deg = (data[2]<<8|data[1])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void download_flash(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	transmit_flash_data();
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void wipe_flash(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	erase_flash(&flash);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void start_logging(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	LOGGING_ACTIVE = 1;
	HAL_GPIO_WritePin(LED_TELEM_PORT, LED_TELEM_PIN, GPIO_PIN_SET);
	add_test_delimiter(&flash);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void stop_logging(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	LOGGING_ACTIVE = 0;
	finish_flash_write(&flash);
	HAL_GPIO_WritePin(LED_FLASH_LOGGING_PORT, LED_FLASH_LOGGING_PIN, GPIO_PIN_RESET);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_stepper_pos(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	float position = (data[4]<<24|data[3]<<16|data[2]<<8|data[1])/100.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
		L6470_goto_motor_pos(&(tanks[motor_num].motor), position);
		// TODO: update packet values
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_stepper_zero(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
		L6470_zero_motor(&(tanks[motor_num].motor));
		// TODO: update position + packet values
	}

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_control_target_pressure(uint8_t* data, uint8_t* status){

	uint8_t tank_num = (data[0])/1;
	float target_pressure = (data[4]<<24|data[3]<<16|data[2]<<8|data[1])/1000.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (tank_num < NUM_TANKS) {
		tanks[tank_num].target_pres = target_pressure;
		save_nonvolatile_variables();
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void ambientize_pressure_transducers(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	for (uint8_t i = 0; i < NUM_PTS; i++) {
		pt_ambients[i] = pressure[i] + pt_ambients[i];
	}
	save_nonvolatile_variables();
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_low_toggle_percent(uint8_t* data, uint8_t* status){

	uint8_t tank_num = (data[0])/1;
	float lower_threshold_pct = (data[4]<<24|data[3]<<16|data[2]<<8|data[1])/1000.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (tank_num < NUM_TANKS) {
		tanks[tank_num].PID_ctrl_vlv_low_pres = tanks[tank_num].target_pres
				* lower_threshold_pct;
		save_nonvolatile_variables();
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_high_toggle_percent(uint8_t* data, uint8_t* status){

	uint8_t tank_num = (data[0])/1;
	float upper_threshold_pct = (data[4]<<24|data[3]<<16|data[2]<<8|data[1])/1000.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (tank_num < NUM_TANKS) {
		tanks[tank_num].PID_ctrl_vlv_high_pres = tanks[tank_num].target_pres
				* upper_threshold_pct;
		save_nonvolatile_variables();
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_control_loop_duration(uint8_t* data, uint8_t* status){

	uint32_t duration = (data[3]<<24|data[2]<<16|data[1]<<8|data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_stepper_speed(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	uint16_t target_speed = (data[2]<<8|data[1])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
		//L6470_set_motor_max_speed(motor, target_speed)
	}

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_telem(uint8_t* data, uint8_t* status){

	uint8_t state = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// Toggle telem on/off
	if (telem_disabled) {
		telem_disabled = 0;
	}
	else {
		telem_disabled = 1;
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_presstank_status(uint8_t* data, uint8_t* status){

	uint8_t tank_num = (data[0])/1;
	uint8_t state = (data[1])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (tank_num < NUM_TANKS) {
		tanks[tank_num].tank_enable = state;
		save_nonvolatile_variables();
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void ambientize_pot(uint8_t* data, uint8_t* status){

	uint8_t pot_num = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	for (uint8_t i = 0; i < NUM_POTS; i++) {
		// flip pot sign to decouple direction with motor before applying ambient
		pot_ambients[i] = -epot[i]+pot_ambients[i];
	}
	save_nonvolatile_variables();
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_system_clock(uint8_t* data, uint8_t* status){

	uint32_t system_time = (data[3]<<24|data[2]<<16|data[1]<<8|data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	__HAL_TIM_SetCounter(&TIM_MICROS, system_time);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

