// Autogenerated by firmware-libraries/SerialComms/python/cmd_template_parser.py on Fri Jul 16 23:33:51 2021

#include "pack_cmd_defines.h"
Cmd_Pointer cmds_ptr[NUM_CMD_ITEMS] = {

set_vlv,
set_kp,
set_ki,
set_kd,
set_state,
download_flash,
wipe_flash,
start_logging,
stop_logging,
set_stepper_pos,
set_stepper_zero,
set_control_target_pressure,
ambientize_pressure_transducers,
set_low_toggle_percent,
set_high_toggle_percent,
set_stepper_speed,
set_telem,
set_presstank_status,
ambientize_pot,
set_system_clock,
remove_pressure_ambients,
set_autosequence_fuel_first,
set_autosequence_lox_first,
set_autosequence_mpv_delay,
set_engine_test_duration,
set_engine_purge_duration,
clear_status_flags,
start_simulation,
advance_simulation,
stop_simulation
};

int16_t command_map[COMMAND_MAP_SZ] = {-1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1, 1, 2, 3, -1, 4, -1, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, -1, 15, 16, 17, 18, -1, -1, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
int16_t command_sz[COMMAND_MAP_SZ] = {-1, -1, -1, -1, -1, -1, -1, -1, 17, -1, -1, -1, -1, 21, 21, 21, -1, 13, -1, 12, 12, 12, 12, 17, 13, 17, 12, 17, 17, -1, 15, 13, 14, 13, -1, -1, 16, 12, 12, 12, 14, 16, 16, 12, 12, 12, 12};
