// Autogenerated by firmware-libraries/SerialComms/python/cmd_template_parser.py on Mon Jul  5 19:57:35 2021

#include <stdint.h>

// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
#include "autosequence.h"  // for set_state()
#include "serial_data.h"  // flash and telem
#include "globals.h"  // for setting constants
#include "valves.h"  // manual valve control
#include "constants.h"
#include "motors.h"  // is this file even needed anymore?
#include "status_flags.h"
#include "tank_pressure_control.h"
//#include "sensors.h"  // ambients


extern TIM_HandleTypeDef TIM_MICROS;

// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

void set_vlv(uint8_t* data, uint8_t* status){

	uint32_t vlv_num = (data[3]<<24|data[2]<<16|data[1]<<8|data[0])/1;
	uint8_t state = (data[4])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	set_valve_channel(vlv_num, state);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_kp(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	double gain = (data[8]<<56|data[7]<<48|data[6]<<40|data[5]<<32|data[4]<<24|data[3]<<16|data[2]<<8|data[1])/100.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
		mtr_kp[motor_num] = gain;  // telem
		tanks[motor_num].K_p = gain;  // control
	}
	// TODO: save flash constants
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_ki(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	double gain = (data[8]<<56|data[7]<<48|data[6]<<40|data[5]<<32|data[4]<<24|data[3]<<16|data[2]<<8|data[1])/100.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
			mtr_ki[motor_num] = gain;  // telem
			tanks[motor_num].K_i = gain;  // control
		}
	// TODO: save flash constants
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_kd(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	double gain = (data[8]<<56|data[7]<<48|data[6]<<40|data[5]<<32|data[4]<<24|data[3]<<16|data[2]<<8|data[1])/100.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (motor_num < NUM_MOTORS) {
			mtr_kd[motor_num] = gain;  // telem
			tanks[motor_num].K_d = gain;  // control
		}
	// TODO: save flash constants
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_state(uint8_t* data, uint8_t* status){

	uint8_t next_state = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	manual_state_transition(next_state);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void download_flash(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	transmit_flash_data();
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void wipe_flash(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	erase_flash(&flash);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void start_logging(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	LOGGING_ACTIVE = 1;
	HAL_GPIO_WritePin(LED_TELEM_PORT, LED_TELEM_PIN, GPIO_PIN_SET);
	add_test_delimiter(&flash);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void stop_logging(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	LOGGING_ACTIVE = 0;
	finish_flash_write(&flash);
	HAL_GPIO_WritePin(LED_TELEM_PORT, LED_TELEM_PIN, GPIO_PIN_RESET);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_stepper_pos(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	float position = (data[4]<<24|data[3]<<16|data[2]<<8|data[1])/100.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO after writing motor library

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_stepper_zero(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO after writing motor library

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_control_target_pressure(uint8_t* data, uint8_t* status){

	uint8_t tank_num = (data[0])/1;
	float target_pressure = (data[4]<<24|data[3]<<16|data[2]<<8|data[1])/1000.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	if (tank_num < NUM_TANKS) {
		tanks[tank_num].target_pres = target_pressure;
	}
	// TODO write flash constants
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void ambientize_pressure_transducers(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO after calibrations

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_low_toggle_percent(uint8_t* data, uint8_t* status){

	uint8_t tank_num = (data[0])/1;
	float lower_threshold_pct = (data[4]<<24|data[3]<<16|data[2]<<8|data[1])/1000.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	//if (tank_num < NUM_TANKS) {
	//	tanks[tank_num].
	//}

	// write flash constants
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_high_toggle_percent(uint8_t* data, uint8_t* status){

	uint8_t tank_num = (data[0])/1;
	float upper_threshold_pct = (data[4]<<24|data[3]<<16|data[2]<<8|data[1])/1000.0;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO

	// write flash constants
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_stepper_speed(uint8_t* data, uint8_t* status){

	uint8_t motor_num = (data[0])/1;
	uint16_t target_speed = (data[2]<<8|data[1])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO after writing motor library

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_telem(uint8_t* data, uint8_t* status){

	uint8_t state = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// Toggle telem on/off
	if (disable_telem) {
		disable_telem = 0;
	}
	else {
		disable_telem = 1;
	}
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_presstank_status(uint8_t* data, uint8_t* status){

	uint8_t tank_num = (data[0])/1;
	uint8_t state = (data[1])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO figure out tank enable structure

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void ambientize_pot(uint8_t* data, uint8_t* status){

	uint8_t pot_num = (data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO: after calibrations

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_system_clock(uint8_t* data, uint8_t* status){

	uint32_t system_time = (data[3]<<24|data[2]<<16|data[1]<<8|data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	__HAL_TIM_SetCounter(&TIM_MICROS, system_time);
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void remove_pressure_ambients(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO after new calibrations

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_autosequence_fuel_first(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_autosequence_lox_first(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO: how to integrate with autosequence structure

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_autosequence_mpv_delay(uint8_t* data, uint8_t* status){

	uint16_t mpv_delay_ms = (data[1]<<8|data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO: how to integrate with autosequence structure

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_engine_test_duration(uint8_t* data, uint8_t* status){

	uint32_t engine_test_duration = (data[3]<<24|data[2]<<16|data[1]<<8|data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO: how to integrate with autosequence structure

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void set_engine_purge_duration(uint8_t* data, uint8_t* status){

	uint32_t engine_purge_duration = (data[3]<<24|data[2]<<16|data[1]<<8|data[0])/1;
	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	// TODO: how to integrate with autosequence structure

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void clear_status_flags(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED
	status_flags = 0;
	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void start_simulation(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void advance_simulation(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

void stop_simulation(uint8_t* data, uint8_t* status){

	
	// USER CODE BEGIN - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

	// USER CODE END - MODIFICATIONS OUTSIDE THIS SECTION WILL BE DELETED

}

