/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// pack_calibration_defines.h
/// Autogenerated by firmware-libraries/SerialComms/python/calibration_file_generator.py on Tue Aug  3 23:31:37 2021

#ifndef PACK_CALIBRATION_DEFINES_H
#define PACK_CALIBRATION_DEFINES_H

#include "calibrations.h"
#include <stdint.h>

#define	CALIBRATION_ITEM_0	((int16_t) (pt_cal_lower_voltage[0]*10)) >> 0 
#define	CALIBRATION_ITEM_1	((int16_t) (pt_cal_lower_voltage[0]*10)) >> 8 
#define	CALIBRATION_ITEM_2	((int16_t) (pt_cal_lower_voltage[1]*10)) >> 0 
#define	CALIBRATION_ITEM_3	((int16_t) (pt_cal_lower_voltage[1]*10)) >> 8 
#define	CALIBRATION_ITEM_4	((int16_t) (pt_cal_lower_voltage[2]*10)) >> 0 
#define	CALIBRATION_ITEM_5	((int16_t) (pt_cal_lower_voltage[2]*10)) >> 8 
#define	CALIBRATION_ITEM_6	((int16_t) (pt_cal_lower_voltage[3]*10)) >> 0 
#define	CALIBRATION_ITEM_7	((int16_t) (pt_cal_lower_voltage[3]*10)) >> 8 
#define	CALIBRATION_ITEM_8	((int16_t) (pt_cal_lower_voltage[4]*10)) >> 0 
#define	CALIBRATION_ITEM_9	((int16_t) (pt_cal_lower_voltage[4]*10)) >> 8 
#define	CALIBRATION_ITEM_10	((int16_t) (pt_cal_lower_voltage[5]*10)) >> 0 
#define	CALIBRATION_ITEM_11	((int16_t) (pt_cal_lower_voltage[5]*10)) >> 8 
#define	CALIBRATION_ITEM_12	((int16_t) (pt_cal_lower_voltage[6]*10)) >> 0 
#define	CALIBRATION_ITEM_13	((int16_t) (pt_cal_lower_voltage[6]*10)) >> 8 
#define	CALIBRATION_ITEM_14	((int16_t) (pt_cal_lower_voltage[7]*10)) >> 0 
#define	CALIBRATION_ITEM_15	((int16_t) (pt_cal_lower_voltage[7]*10)) >> 8 
#define	CALIBRATION_ITEM_16	((int16_t) (pt_cal_lower_voltage[8]*10)) >> 0 
#define	CALIBRATION_ITEM_17	((int16_t) (pt_cal_lower_voltage[8]*10)) >> 8 
#define	CALIBRATION_ITEM_18	((int16_t) (pt_cal_lower_voltage[9]*10)) >> 0 
#define	CALIBRATION_ITEM_19	((int16_t) (pt_cal_lower_voltage[9]*10)) >> 8 
#define	CALIBRATION_ITEM_20	((int16_t) (pt_cal_lower_voltage[10]*10)) >> 0 
#define	CALIBRATION_ITEM_21	((int16_t) (pt_cal_lower_voltage[10]*10)) >> 8 
#define	CALIBRATION_ITEM_22	((int16_t) (pt_cal_lower_voltage[11]*10)) >> 0 
#define	CALIBRATION_ITEM_23	((int16_t) (pt_cal_lower_voltage[11]*10)) >> 8 
#define	CALIBRATION_ITEM_24	((int16_t) (pt_cal_lower_voltage[12]*10)) >> 0 
#define	CALIBRATION_ITEM_25	((int16_t) (pt_cal_lower_voltage[12]*10)) >> 8 
#define	CALIBRATION_ITEM_26	((int16_t) (pt_cal_lower_voltage[13]*10)) >> 0 
#define	CALIBRATION_ITEM_27	((int16_t) (pt_cal_lower_voltage[13]*10)) >> 8 
#define	CALIBRATION_ITEM_28	((int16_t) (pt_cal_lower_voltage[14]*10)) >> 0 
#define	CALIBRATION_ITEM_29	((int16_t) (pt_cal_lower_voltage[14]*10)) >> 8 
#define	CALIBRATION_ITEM_30	((int16_t) (pt_cal_lower_voltage[15]*10)) >> 0 
#define	CALIBRATION_ITEM_31	((int16_t) (pt_cal_lower_voltage[15]*10)) >> 8 
#define	CALIBRATION_ITEM_32	((int16_t) (pt_cal_lower_voltage[16]*10)) >> 0 
#define	CALIBRATION_ITEM_33	((int16_t) (pt_cal_lower_voltage[16]*10)) >> 8 
#define	CALIBRATION_ITEM_34	((int16_t) (pt_cal_lower_voltage[17]*10)) >> 0 
#define	CALIBRATION_ITEM_35	((int16_t) (pt_cal_lower_voltage[17]*10)) >> 8 
#define	CALIBRATION_ITEM_36	((int16_t) (pt_cal_lower_voltage[18]*10)) >> 0 
#define	CALIBRATION_ITEM_37	((int16_t) (pt_cal_lower_voltage[18]*10)) >> 8 
#define	CALIBRATION_ITEM_38	((int16_t) (pt_cal_lower_voltage[19]*10)) >> 0 
#define	CALIBRATION_ITEM_39	((int16_t) (pt_cal_lower_voltage[19]*10)) >> 8 
#define	CALIBRATION_ITEM_40	((int16_t) (pt_cal_lower_voltage[20]*10)) >> 0 
#define	CALIBRATION_ITEM_41	((int16_t) (pt_cal_lower_voltage[20]*10)) >> 8 
#define	CALIBRATION_ITEM_42	((int16_t) (pt_cal_lower_voltage[21]*10)) >> 0 
#define	CALIBRATION_ITEM_43	((int16_t) (pt_cal_lower_voltage[21]*10)) >> 8 
#define	CALIBRATION_ITEM_44	((int16_t) (pt_cal_upper_voltage[0]*10)) >> 0 
#define	CALIBRATION_ITEM_45	((int16_t) (pt_cal_upper_voltage[0]*10)) >> 8 
#define	CALIBRATION_ITEM_46	((int16_t) (pt_cal_upper_voltage[1]*10)) >> 0 
#define	CALIBRATION_ITEM_47	((int16_t) (pt_cal_upper_voltage[1]*10)) >> 8 
#define	CALIBRATION_ITEM_48	((int16_t) (pt_cal_upper_voltage[2]*10)) >> 0 
#define	CALIBRATION_ITEM_49	((int16_t) (pt_cal_upper_voltage[2]*10)) >> 8 
#define	CALIBRATION_ITEM_50	((int16_t) (pt_cal_upper_voltage[3]*10)) >> 0 
#define	CALIBRATION_ITEM_51	((int16_t) (pt_cal_upper_voltage[3]*10)) >> 8 
#define	CALIBRATION_ITEM_52	((int16_t) (pt_cal_upper_voltage[4]*10)) >> 0 
#define	CALIBRATION_ITEM_53	((int16_t) (pt_cal_upper_voltage[4]*10)) >> 8 
#define	CALIBRATION_ITEM_54	((int16_t) (pt_cal_upper_voltage[5]*10)) >> 0 
#define	CALIBRATION_ITEM_55	((int16_t) (pt_cal_upper_voltage[5]*10)) >> 8 
#define	CALIBRATION_ITEM_56	((int16_t) (pt_cal_upper_voltage[6]*10)) >> 0 
#define	CALIBRATION_ITEM_57	((int16_t) (pt_cal_upper_voltage[6]*10)) >> 8 
#define	CALIBRATION_ITEM_58	((int16_t) (pt_cal_upper_voltage[7]*10)) >> 0 
#define	CALIBRATION_ITEM_59	((int16_t) (pt_cal_upper_voltage[7]*10)) >> 8 
#define	CALIBRATION_ITEM_60	((int16_t) (pt_cal_upper_voltage[8]*10)) >> 0 
#define	CALIBRATION_ITEM_61	((int16_t) (pt_cal_upper_voltage[8]*10)) >> 8 
#define	CALIBRATION_ITEM_62	((int16_t) (pt_cal_upper_voltage[9]*10)) >> 0 
#define	CALIBRATION_ITEM_63	((int16_t) (pt_cal_upper_voltage[9]*10)) >> 8 
#define	CALIBRATION_ITEM_64	((int16_t) (pt_cal_upper_voltage[10]*10)) >> 0 
#define	CALIBRATION_ITEM_65	((int16_t) (pt_cal_upper_voltage[10]*10)) >> 8 
#define	CALIBRATION_ITEM_66	((int16_t) (pt_cal_upper_voltage[11]*10)) >> 0 
#define	CALIBRATION_ITEM_67	((int16_t) (pt_cal_upper_voltage[11]*10)) >> 8 
#define	CALIBRATION_ITEM_68	((int16_t) (pt_cal_upper_voltage[12]*10)) >> 0 
#define	CALIBRATION_ITEM_69	((int16_t) (pt_cal_upper_voltage[12]*10)) >> 8 
#define	CALIBRATION_ITEM_70	((int16_t) (pt_cal_upper_voltage[13]*10)) >> 0 
#define	CALIBRATION_ITEM_71	((int16_t) (pt_cal_upper_voltage[13]*10)) >> 8 
#define	CALIBRATION_ITEM_72	((int16_t) (pt_cal_upper_voltage[14]*10)) >> 0 
#define	CALIBRATION_ITEM_73	((int16_t) (pt_cal_upper_voltage[14]*10)) >> 8 
#define	CALIBRATION_ITEM_74	((int16_t) (pt_cal_upper_voltage[15]*10)) >> 0 
#define	CALIBRATION_ITEM_75	((int16_t) (pt_cal_upper_voltage[15]*10)) >> 8 
#define	CALIBRATION_ITEM_76	((int16_t) (pt_cal_upper_voltage[16]*10)) >> 0 
#define	CALIBRATION_ITEM_77	((int16_t) (pt_cal_upper_voltage[16]*10)) >> 8 
#define	CALIBRATION_ITEM_78	((int16_t) (pt_cal_upper_voltage[17]*10)) >> 0 
#define	CALIBRATION_ITEM_79	((int16_t) (pt_cal_upper_voltage[17]*10)) >> 8 
#define	CALIBRATION_ITEM_80	((int16_t) (pt_cal_upper_voltage[18]*10)) >> 0 
#define	CALIBRATION_ITEM_81	((int16_t) (pt_cal_upper_voltage[18]*10)) >> 8 
#define	CALIBRATION_ITEM_82	((int16_t) (pt_cal_upper_voltage[19]*10)) >> 0 
#define	CALIBRATION_ITEM_83	((int16_t) (pt_cal_upper_voltage[19]*10)) >> 8 
#define	CALIBRATION_ITEM_84	((int16_t) (pt_cal_upper_voltage[20]*10)) >> 0 
#define	CALIBRATION_ITEM_85	((int16_t) (pt_cal_upper_voltage[20]*10)) >> 8 
#define	CALIBRATION_ITEM_86	((int16_t) (pt_cal_upper_voltage[21]*10)) >> 0 
#define	CALIBRATION_ITEM_87	((int16_t) (pt_cal_upper_voltage[21]*10)) >> 8 
#define	CALIBRATION_ITEM_88	((int16_t) (pt_cal_upper_pressure[0]*1)) >> 0 
#define	CALIBRATION_ITEM_89	((int16_t) (pt_cal_upper_pressure[0]*1)) >> 8 
#define	CALIBRATION_ITEM_90	((int16_t) (pt_cal_upper_pressure[1]*1)) >> 0 
#define	CALIBRATION_ITEM_91	((int16_t) (pt_cal_upper_pressure[1]*1)) >> 8 
#define	CALIBRATION_ITEM_92	((int16_t) (pt_cal_upper_pressure[2]*1)) >> 0 
#define	CALIBRATION_ITEM_93	((int16_t) (pt_cal_upper_pressure[2]*1)) >> 8 
#define	CALIBRATION_ITEM_94	((int16_t) (pt_cal_upper_pressure[3]*1)) >> 0 
#define	CALIBRATION_ITEM_95	((int16_t) (pt_cal_upper_pressure[3]*1)) >> 8 
#define	CALIBRATION_ITEM_96	((int16_t) (pt_cal_upper_pressure[4]*1)) >> 0 
#define	CALIBRATION_ITEM_97	((int16_t) (pt_cal_upper_pressure[4]*1)) >> 8 
#define	CALIBRATION_ITEM_98	((int16_t) (pt_cal_upper_pressure[5]*1)) >> 0 
#define	CALIBRATION_ITEM_99	((int16_t) (pt_cal_upper_pressure[5]*1)) >> 8 
#define	CALIBRATION_ITEM_100	((int16_t) (pt_cal_upper_pressure[6]*1)) >> 0 
#define	CALIBRATION_ITEM_101	((int16_t) (pt_cal_upper_pressure[6]*1)) >> 8 
#define	CALIBRATION_ITEM_102	((int16_t) (pt_cal_upper_pressure[7]*1)) >> 0 
#define	CALIBRATION_ITEM_103	((int16_t) (pt_cal_upper_pressure[7]*1)) >> 8 
#define	CALIBRATION_ITEM_104	((int16_t) (pt_cal_upper_pressure[8]*1)) >> 0 
#define	CALIBRATION_ITEM_105	((int16_t) (pt_cal_upper_pressure[8]*1)) >> 8 
#define	CALIBRATION_ITEM_106	((int16_t) (pt_cal_upper_pressure[9]*1)) >> 0 
#define	CALIBRATION_ITEM_107	((int16_t) (pt_cal_upper_pressure[9]*1)) >> 8 
#define	CALIBRATION_ITEM_108	((int16_t) (pt_cal_upper_pressure[10]*1)) >> 0 
#define	CALIBRATION_ITEM_109	((int16_t) (pt_cal_upper_pressure[10]*1)) >> 8 
#define	CALIBRATION_ITEM_110	((int16_t) (pt_cal_upper_pressure[11]*1)) >> 0 
#define	CALIBRATION_ITEM_111	((int16_t) (pt_cal_upper_pressure[11]*1)) >> 8 
#define	CALIBRATION_ITEM_112	((int16_t) (pt_cal_upper_pressure[12]*1)) >> 0 
#define	CALIBRATION_ITEM_113	((int16_t) (pt_cal_upper_pressure[12]*1)) >> 8 
#define	CALIBRATION_ITEM_114	((int16_t) (pt_cal_upper_pressure[13]*1)) >> 0 
#define	CALIBRATION_ITEM_115	((int16_t) (pt_cal_upper_pressure[13]*1)) >> 8 
#define	CALIBRATION_ITEM_116	((int16_t) (pt_cal_upper_pressure[14]*1)) >> 0 
#define	CALIBRATION_ITEM_117	((int16_t) (pt_cal_upper_pressure[14]*1)) >> 8 
#define	CALIBRATION_ITEM_118	((int16_t) (pt_cal_upper_pressure[15]*1)) >> 0 
#define	CALIBRATION_ITEM_119	((int16_t) (pt_cal_upper_pressure[15]*1)) >> 8 
#define	CALIBRATION_ITEM_120	((int16_t) (pt_cal_upper_pressure[16]*1)) >> 0 
#define	CALIBRATION_ITEM_121	((int16_t) (pt_cal_upper_pressure[16]*1)) >> 8 
#define	CALIBRATION_ITEM_122	((int16_t) (pt_cal_upper_pressure[17]*1)) >> 0 
#define	CALIBRATION_ITEM_123	((int16_t) (pt_cal_upper_pressure[17]*1)) >> 8 
#define	CALIBRATION_ITEM_124	((int16_t) (pt_cal_upper_pressure[18]*1)) >> 0 
#define	CALIBRATION_ITEM_125	((int16_t) (pt_cal_upper_pressure[18]*1)) >> 8 
#define	CALIBRATION_ITEM_126	((int16_t) (pt_cal_upper_pressure[19]*1)) >> 0 
#define	CALIBRATION_ITEM_127	((int16_t) (pt_cal_upper_pressure[19]*1)) >> 8 
#define	CALIBRATION_ITEM_128	((int16_t) (pt_cal_upper_pressure[20]*1)) >> 0 
#define	CALIBRATION_ITEM_129	((int16_t) (pt_cal_upper_pressure[20]*1)) >> 8 
#define	CALIBRATION_ITEM_130	((int16_t) (pt_cal_upper_pressure[21]*1)) >> 0 
#define	CALIBRATION_ITEM_131	((int16_t) (pt_cal_upper_pressure[21]*1)) >> 8 
#define	CLB_NUM_CALIBRATION_ITEMS	132

/**
 * Takes in a uint8_t array of size CLB_NUM_CALIBRATION_ITEMS and packs the 
 * global variables into it as defined in pack_calibration_defines.h
 *
 * @param dst	<uint8_t*>	Array to write the global variables to after packing their bytes for calibrations.
**/
extern void pack_calibration_data(uint8_t* dst);

#endif
