/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// pack_calibration_defines.h
/// Autogenerated by firmware-libraries/SerialComms/python/calibration_file_generator.py on Sun Aug 22 17:24:44 2021

#include "calibrations.h"
#include <stdint.h>

#define	CALIBRATION_ITEM_0	((int32_t) (pt_cal_slope[0]*10000)) >> 0 
#define	CALIBRATION_ITEM_1	((int32_t) (pt_cal_slope[0]*10000)) >> 8 
#define	CALIBRATION_ITEM_2	((int32_t) (pt_cal_slope[0]*10000)) >> 16 
#define	CALIBRATION_ITEM_3	((int32_t) (pt_cal_slope[0]*10000)) >> 24 
#define	CALIBRATION_ITEM_4	((int32_t) (pt_cal_slope[1]*10000)) >> 0 
#define	CALIBRATION_ITEM_5	((int32_t) (pt_cal_slope[1]*10000)) >> 8 
#define	CALIBRATION_ITEM_6	((int32_t) (pt_cal_slope[1]*10000)) >> 16 
#define	CALIBRATION_ITEM_7	((int32_t) (pt_cal_slope[1]*10000)) >> 24 
#define	CALIBRATION_ITEM_8	((int32_t) (pt_cal_slope[2]*10000)) >> 0 
#define	CALIBRATION_ITEM_9	((int32_t) (pt_cal_slope[2]*10000)) >> 8 
#define	CALIBRATION_ITEM_10	((int32_t) (pt_cal_slope[2]*10000)) >> 16 
#define	CALIBRATION_ITEM_11	((int32_t) (pt_cal_slope[2]*10000)) >> 24 
#define	CALIBRATION_ITEM_12	((int32_t) (pt_cal_slope[3]*10000)) >> 0 
#define	CALIBRATION_ITEM_13	((int32_t) (pt_cal_slope[3]*10000)) >> 8 
#define	CALIBRATION_ITEM_14	((int32_t) (pt_cal_slope[3]*10000)) >> 16 
#define	CALIBRATION_ITEM_15	((int32_t) (pt_cal_slope[3]*10000)) >> 24 
#define	CALIBRATION_ITEM_16	((int32_t) (pt_cal_slope[4]*10000)) >> 0 
#define	CALIBRATION_ITEM_17	((int32_t) (pt_cal_slope[4]*10000)) >> 8 
#define	CALIBRATION_ITEM_18	((int32_t) (pt_cal_slope[4]*10000)) >> 16 
#define	CALIBRATION_ITEM_19	((int32_t) (pt_cal_slope[4]*10000)) >> 24 
#define	CALIBRATION_ITEM_20	((int32_t) (pt_cal_slope[5]*10000)) >> 0 
#define	CALIBRATION_ITEM_21	((int32_t) (pt_cal_slope[5]*10000)) >> 8 
#define	CALIBRATION_ITEM_22	((int32_t) (pt_cal_slope[5]*10000)) >> 16 
#define	CALIBRATION_ITEM_23	((int32_t) (pt_cal_slope[5]*10000)) >> 24 
#define	CALIBRATION_ITEM_24	((int16_t) (pt_cal_offset[0]*1)) >> 0 
#define	CALIBRATION_ITEM_25	((int16_t) (pt_cal_offset[0]*1)) >> 8 
#define	CALIBRATION_ITEM_26	((int16_t) (pt_cal_offset[1]*1)) >> 0 
#define	CALIBRATION_ITEM_27	((int16_t) (pt_cal_offset[1]*1)) >> 8 
#define	CALIBRATION_ITEM_28	((int16_t) (pt_cal_offset[2]*1)) >> 0 
#define	CALIBRATION_ITEM_29	((int16_t) (pt_cal_offset[2]*1)) >> 8 
#define	CALIBRATION_ITEM_30	((int16_t) (pt_cal_offset[3]*1)) >> 0 
#define	CALIBRATION_ITEM_31	((int16_t) (pt_cal_offset[3]*1)) >> 8 
#define	CALIBRATION_ITEM_32	((int16_t) (pt_cal_offset[4]*1)) >> 0 
#define	CALIBRATION_ITEM_33	((int16_t) (pt_cal_offset[4]*1)) >> 8 
#define	CALIBRATION_ITEM_34	((int16_t) (pt_cal_offset[5]*1)) >> 0 
#define	CALIBRATION_ITEM_35	((int16_t) (pt_cal_offset[5]*1)) >> 8 
#define	CLB_NUM_CALIBRATION_ITEMS	36

/**
 * Takes in a uint8_t array of size CLB_NUM_CALIBRATION_ITEMS and packs the 
 * global variables into it as defined in pack_calibration_defines.h
 *
 * @param dst	<uint8_t*>	Array to write the global variables to after packing their bytes for calibrations.
**/
extern void pack_calibration_data(uint8_t* dst);
