/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// pack_calibration_defines.h
/// Autogenerated by firmware-libraries/SerialComms/python/calibration_file_generator.py on Mon Aug  9 00:35:42 2021

#include "calibrations.h"
#include <stdint.h>

#define	CALIBRATION_ITEM_0	((int16_t) (pt_cal_lower_voltage[0]*10)) >> 0 
#define	CALIBRATION_ITEM_1	((int16_t) (pt_cal_lower_voltage[0]*10)) >> 8 
#define	CALIBRATION_ITEM_2	((int16_t) (pt_cal_lower_voltage[1]*10)) >> 0 
#define	CALIBRATION_ITEM_3	((int16_t) (pt_cal_lower_voltage[1]*10)) >> 8 
#define	CALIBRATION_ITEM_4	((int16_t) (pt_cal_lower_voltage[2]*10)) >> 0 
#define	CALIBRATION_ITEM_5	((int16_t) (pt_cal_lower_voltage[2]*10)) >> 8 
#define	CALIBRATION_ITEM_6	((int16_t) (pt_cal_lower_voltage[3]*10)) >> 0 
#define	CALIBRATION_ITEM_7	((int16_t) (pt_cal_lower_voltage[3]*10)) >> 8 
#define	CALIBRATION_ITEM_8	((int16_t) (pt_cal_lower_voltage[4]*10)) >> 0 
#define	CALIBRATION_ITEM_9	((int16_t) (pt_cal_lower_voltage[4]*10)) >> 8 
#define	CALIBRATION_ITEM_10	((int16_t) (pt_cal_lower_voltage[5]*10)) >> 0 
#define	CALIBRATION_ITEM_11	((int16_t) (pt_cal_lower_voltage[5]*10)) >> 8 
#define	CALIBRATION_ITEM_12	((int16_t) (pt_cal_upper_voltage[0]*10)) >> 0 
#define	CALIBRATION_ITEM_13	((int16_t) (pt_cal_upper_voltage[0]*10)) >> 8 
#define	CALIBRATION_ITEM_14	((int16_t) (pt_cal_upper_voltage[1]*10)) >> 0 
#define	CALIBRATION_ITEM_15	((int16_t) (pt_cal_upper_voltage[1]*10)) >> 8 
#define	CALIBRATION_ITEM_16	((int16_t) (pt_cal_upper_voltage[2]*10)) >> 0 
#define	CALIBRATION_ITEM_17	((int16_t) (pt_cal_upper_voltage[2]*10)) >> 8 
#define	CALIBRATION_ITEM_18	((int16_t) (pt_cal_upper_voltage[3]*10)) >> 0 
#define	CALIBRATION_ITEM_19	((int16_t) (pt_cal_upper_voltage[3]*10)) >> 8 
#define	CALIBRATION_ITEM_20	((int16_t) (pt_cal_upper_voltage[4]*10)) >> 0 
#define	CALIBRATION_ITEM_21	((int16_t) (pt_cal_upper_voltage[4]*10)) >> 8 
#define	CALIBRATION_ITEM_22	((int16_t) (pt_cal_upper_voltage[5]*10)) >> 0 
#define	CALIBRATION_ITEM_23	((int16_t) (pt_cal_upper_voltage[5]*10)) >> 8 
#define	CALIBRATION_ITEM_24	((int16_t) (pt_cal_upper_pressure[0]*1)) >> 0 
#define	CALIBRATION_ITEM_25	((int16_t) (pt_cal_upper_pressure[0]*1)) >> 8 
#define	CALIBRATION_ITEM_26	((int16_t) (pt_cal_upper_pressure[1]*1)) >> 0 
#define	CALIBRATION_ITEM_27	((int16_t) (pt_cal_upper_pressure[1]*1)) >> 8 
#define	CALIBRATION_ITEM_28	((int16_t) (pt_cal_upper_pressure[2]*1)) >> 0 
#define	CALIBRATION_ITEM_29	((int16_t) (pt_cal_upper_pressure[2]*1)) >> 8 
#define	CALIBRATION_ITEM_30	((int16_t) (pt_cal_upper_pressure[3]*1)) >> 0 
#define	CALIBRATION_ITEM_31	((int16_t) (pt_cal_upper_pressure[3]*1)) >> 8 
#define	CALIBRATION_ITEM_32	((int16_t) (pt_cal_upper_pressure[4]*1)) >> 0 
#define	CALIBRATION_ITEM_33	((int16_t) (pt_cal_upper_pressure[4]*1)) >> 8 
#define	CALIBRATION_ITEM_34	((int16_t) (pt_cal_upper_pressure[5]*1)) >> 0 
#define	CALIBRATION_ITEM_35	((int16_t) (pt_cal_upper_pressure[5]*1)) >> 8 
#define	CLB_NUM_CALIBRATION_ITEMS	36

/**
 * Takes in a uint8_t array of size CLB_NUM_CALIBRATION_ITEMS and packs the 
 * global variables into it as defined in pack_calibration_defines.h
 *
 * @param dst	<uint8_t*>	Array to write the global variables to after packing their bytes for calibrations.
**/
extern void pack_calibration_data(uint8_t* dst);
