/*
 * serial_data.h
 *
 *  Created on: May 18, 2021
 *      Author: natha
 *
 */

#ifndef INC_SERIAL_DATA_H_
#define INC_SERIAL_DATA_H_

#include <stdint.h>
#include "W25N01GV.h"
#include "stm32f4xx.h"

W25N01GV_Flash flash;
uint8_t disable_telem;  // Toggled on during flash dump

/**
 * Inits telemetry stuff and flash.
 */
void init_serial_data();

/**
 * Sends a telemetry packet to an address in blocking mode
 * This function is only ever called with target_addr == SERVER_ADDR,
 * but allows for other addresses for flexibility
 *
 * @param target_addr: Address of board/location to send packet to
 */
void send_telem_packet(uint8_t target_addr);

/**
 * Writes a telemetry packet to flash
 */
void save_flash_packet();

/**
 * Transmits all flash data at once, for a flash dump
 */
void transmit_flash_data();

/**
 * TODO: move this to autogenerated function
 */
void write_flash_constants();

/**
 * TODO: move this to autogenerated function
 */
void read_flash_constants();

#endif /* INC_SERIAL_DATA_H_ */
